version: '3.8'

services:
  web:
    image: tiritibambix/cleanbot-web:latest
    ports:
      - "5392:8080"
    volumes:
      - /srv/Files/Cleanbot/config:/app/config
    environment:
      - FLASK_ENV=production
    networks:
      - cleanbot_network
    restart: unless-stopped

  bot:
    image: tiritibambix/cleanbot:latest
    volumes:
      - /srv/Files/Cleanbot/config:/app/config
    expose:
      - "8081"
    networks:
      - cleanbot_network
    restart: unless-stopped

networks:
  cleanbot_network:
    driver: bridge
