services:
  bot:
    image: tiritibambix/cleanbot:latest
    platform: linux/amd64
    volumes:
      - ./config:/app/config
    ports:
      - "8081:8081"
    networks:
      - cleanbot_network
    depends_on:
      - web
    restart: unless-stopped

  web:
    image: tiritibambix/cleanbot-web:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
    networks:
      - cleanbot_network
    restart: unless-stopped

networks:
  cleanbot_network:
    driver: bridge

volumes:
  config:
