FROM python:3.11-slim

WORKDIR /app

COPY web/requirements.txt .
COPY web/templates ./templates
COPY web/static ./static
COPY web/app.py .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python", "app.py"]
